### ISSUE TITLE
libnvidia-nscq.so mount

### ISSUE THREAD

**Issue by bchess** [NVIDIA/libnvidia-container#130]
It seems to me that `libnvidia-nscq.so` should be included in the list of libraries mounted from the host for version compatibility.

**Comment by dualvtable** [comment]
Hi @bchess - may I ask what is your use-case for `libnvidia-nscq` with containers? The library is used for NVSwitch configuration and query. We currently do not document the public APIs and no known public clients exist today. DCGM (our monitoring product) is the only entity that uses NSCQ for reporting NVSwitch telemetry.

**Comment by bchess** [comment]
Yep its precisely for being able to run dcgmi in a container. datacenter-gpu-manager 2.1.7 ships with `libnvidia-nscq-dcgm.so.450.51.06`. When you run that in a container on a host with 450.80.02 drivers you get this error in syslog:

`nvidia-nvswitch: Version mismatch, kernel version 450.80.02 user version 450.51.06`

This version mismatch is visible here: https://docs.nvidia.com/datacenter/tesla/hgx-software-guide/index.html#nscq

**Comment by dualvtable** [comment]
Right - this is a known issue with 2.1.7 (I need to update the release notes) as we had to ship an older version of `libnvidia-nscq`. This will be fixed in an upcoming release of DCGM (where we no longer ship the library). 

But thanks for reporting this RFE. After some internal discussion with engineering, my assumption that we prefer the `libnvidia-nscq-dcgm` soname was incorrect; instead if available, the one on the host is used. Then, the expected workflow would be that users install `nvidia-fabricmanager` and `libnvidia-nscq` on the host and then `libnvidia-container` needs to inject `libnvidia-nscq` along with the other driver libraries into the container. 

FWIW, currently `dcgmi` will only report the enumeration of the switches and the link state. At this time, we do not provide active telemetry on the switches. 

I will file a ticket internally so we can include this enhancement in the next release. 

Thanks again for reporting.

**Comment by bchess** [comment]
Great, thank you! Yes the preference to loading `libnvidia-nscq` over `libnvidia-nscq-dcgm` aligns with what we've observed. And thank you for the info about NVSwitch telemetry.

**Comment by elezar** [comment]
@bchess as of https://github.com/NVIDIA/libnvidia-container/releases/tag/v1.4.0 `libnvidia-nscq` is included in the container with the `utility` driver capability.

I am closing this issue, but please reopen if the problem persists.
