### ISSUE TITLE
Nvidia-Container-Cli Error: could not start driver service: load library failed: libnvidia-ml.so.1: cannot open 

### ISSUE THREAD

**Issue by kaisark** [NVIDIA/libnvidia-container#135]
I ran into a nvidia-container-cli error (driver issue?) on the Jetson Nano (jetpack 4.5.1/arm64). Originally, I thought there was an error with nvidia_docker, but the problem only occurs when the nvidia runtime is invoked with docker.

Example: Docker
sudo docker run -it --rm --net=host --runtime nvidia  -e DISPLAY=$DISPLAY -v /tmp/.X11-unix/:/tmp/.X11-unix nvcr.io/nvidia/l4t-base:r32.4.4

Error:
docker: Error response from daemon: OCI runtime create failed: container_linux.go:367: starting container process caused: process_linux.go:495: container init caused: Running hook #0:: error running hook: exit status 1, stdout: , stderr: nvidia-container-cli: initialization error: driver error: failed to process request: unknown.

I ran a few diagnostics...

user@nano:~/Downloads/nvidia/sdkm_downloads$ nvidia-container-cli list --libraries
nvidia-container-cli: initialization error: driver error: failed to process request

----------------------------------------------
user@nano:~/Downloads/nvidia/sdkm_downloads$ nvidia-container-cli -k -d /dev/tty info

-- WARNING, the following logs are for debugging purposes only --

I0416 03:07:42.835547 20727 nvc.c:372] initializing library context (version=1.3.3, build=bd9fc3f2b642345301cb2e23de07ec5386232317)
I0416 03:07:42.835653 20727 nvc.c:346] using root /
I0416 03:07:42.835674 20727 nvc.c:347] using ldcache /etc/ld.so.cache
I0416 03:07:42.835697 20727 nvc.c:348] using unprivileged user 1000:994
I0416 03:07:42.835769 20727 nvc.c:389] attempting to load dxcore to see if we are running under Windows Subsystem for Linux (WSL)
I0416 03:07:42.836068 20727 nvc.c:391] dxcore initialization failed, continuing assuming a non-WSL environment
W0416 03:07:42.836381 20727 nvc.c:254] failed to detect NVIDIA devices
W0416 03:07:42.836820 20728 nvc.c:269] failed to set inheritable capabilities
W0416 03:07:42.836886 20728 nvc.c:270] skipping kernel modules load due to failure
I0416 03:07:42.837351 20729 driver.c:101] starting driver service
E0416 03:07:42.837708 20729 driver.c:161] could not start driver service: load library failed: libnvidia-ml.so.1: cannot open shared object file: no such file or directory
I0416 03:07:42.837944 20727 driver.c:196] driver service terminated successfully
nvidia-container-cli: initialization error: driver error: failed to process request

**Comment by elezar** [comment]
Hi @kaisark. Jetson support for libnvidia-container is currently limited to a specific version due to how the platform differs from "standard" platforms in terms of drivers and libraries. Please ensure that you have the version that is included in JetPack installed instead of the version you mention.

We are working on ensuring that later versions of the NVIDIA container runtime can be used on multiple platforms, but we don't as yet have a clear date for when this may be ready.

**Comment by kaisark** [comment]
There were some package version conflicts (apt package repository issue), so I uninstalled and reinstalled nvidia_docker (and related packages) and cleaned up the apt repository issues (disabled some of the auto updates/upgrades, etc). I essentially restored the Jetpack versions of the packages downloaded with nvidia's sdkmanager tool.

nvidia_docker and nvidia_container_cli are working again and I can run nvidia containers from nvidia's container catalog( https://ngc.nvidia.com).

Steps:
1. uninstall nvidia_docker2 (sudo apt remove nvidia_docker) - nvidia_container_toolkit and nvidia-container-runtime also removed in the process
2. sudo apt remove libnvidia-container1
3. sudo dpkg -i libnvidia-container-tools_0.9.0_beta.1_arm64.deb 
4. sudo dpkg -i libnvidia-container-tools_0.9.0_beta.1_arm64.deb 
5. sudo dpkg -i nvidia-container-toolkit_1.0.1-1_arm64.deb 
6. sudo dpkg -i nvidia-container-runtime_3.1.0-1_arm64.deb 
7. sudo dpkg -i nvidia-docker2_2.2.0-1_all.deb 
8. restart docker (sudo systemctl restart docker)

I'll post the solution on the nvidia_docker git repository as well.

**Comment by elezar** [comment]
@kaisark we have recently released version 1.7.0-rc.1 of the NVIDIA Container Toolkit to our experimental repositories. The components of the NVIDIA container stack have been updated with better (packaging) support for Jetson.

If you install `nvidia-docker2=2.8.0~rc.1-1` (which depends on `nvidia-container-toolkit=1.7.0~rc.1-1`) this should also work on your Jetson device.

Note that this will install *both* `libnvidia-container0=0.9.0~beta.1` or `libnvidia-container0=0.10.0+jetpack` as well as `libnvida-container1=1.7.0~rc.1-1`, with `libnvida-container-tools=1.7.0~rc.1-1` selecting the applicable library at runtime.

Since you mention that you were able to solve your problem, I'm closing this issue. Please feel free to reopen it or create a new one if something else comes up.

**Comment by elezar** [comment]
@kaisark the `rc.1` packages have been promoted to GA and are available from our `stable` repositories.

See: https://github.com/NVIDIA/nvidia-container-toolkit/releases/tag/v1.7.0
