### ISSUE TITLE
Configuration option for custom driver installation dir?

### ISSUE THREAD

**Issue by ogoid** [NVIDIA/libnvidia-container#146]
Hi,

[looking at the current libnvidia-container source](https://github.com/NVIDIA/libnvidia-container/search?q=bins_dir+%7C%7C+libs_dir), I see there is some support for custom driver installation directory (with nvidia-smi etc.). However, there doesn't seem any way to specify it from the config.toml file. Could this support be added, if it doesn't exist already?

I ask this because my nvidia driver installation is at /opt/nvidia, as my current distribution offers no package for it and wants to keep /usr/bin,lib folders clean.

**Comment by klueska** [comment]
Actually, the config.toml file is the *only* place to set this other than when calling nvidia-container-cli directly.

it is this field: https://github.com/NVIDIA/nvidia-container-toolkit/blob/master/config/config.toml.ubuntu#L7

That said, this won’t actually help you in your case because even though all of your driver files are installed under /opt, the mount namespace of the driver installation is still rooted at /. So all of your proc files are at /proc and not /opt/proc, for example. Likewise, your dev nodes are still at /dev, not /opt/dev.

This option is intended for working with driver installations installed at a different mount namespace, such that chrooting to that new mount namespace can be done to work with the driver and all of its support files.

The biggest user of this config option is the driver container which installs the driver into a container’s root file system and then mounts the container‘s root back on the host under /run/nvidia/driver.

**Comment by ogoid** [comment]
Thanks. I moved my installation to /opt/nvidia/usr and set root to /opt/nvidia.
