### ISSUE TITLE
Support for Ubuntu 24.04

### ISSUE THREAD

**Issue by mokshmridul** [NVIDIA/libnvidia-container#265]
Ubuntu 24.04 LTS has been released a short while ago, and was wondering if / when we would see support for it under this project. At present, the installer fails due to unsupported version.

**Comment by elezar** [comment]
Please make sure that you're following the up to date instructions here: https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html#installing-with-apt

These should also be compatible with Ubuntu 24.04. If these are failing please provide details so that we can address those.

**Comment by mokshmridul** [comment]
Those are the steps i tried, but will try once again at the end of the week, owing to travels. Thank you.

**Comment by mokshmridul** [comment]
Was able to get this working, and hence closing this request.
